### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [instrumentbible/oscilloscope.js#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by joshstovall** [comment]
Sure!  Admittedly, I am not too familiar with TypeScript. But I'm open to collaboration. 🙂

**Comment by joshstovall** [comment]
I added a list of attributes in the [Wiki](https://github.com/instrumentbible/oscilloscope.js/wiki).   Hopefully that might help help.

**Comment by geopic** [comment]
Great, I'll start on it now. And the API reference is much appreciated man
